### PR TITLE
Creating test framework for evaluation methods

### LINKED ISSUE #63: Create test framework for motion descriptors with library of performance recordings
As we develop more methods for quantifying motion, we need a thorough, systematic way to evaluate, compare, and iterate on them.

Let's develop an automatic testing scheme that can run quantification code against a library of motion performance recordings. We should be able to generate output like in #44 automatically.

This motion library should contain interesting test cases, such as:
- varying levels of overall performance.
- isolated inaccuracies (both positional and temporal).
- different motion _styles_ (perhaps corresponding to LMA efforts)
- different technical recording characteristics (such as pose estimation frequency).

### PR DESCRIPTION
**Pull request by j55blanchet**
As we seek to deepen the computer's understanding of motion data with additional motion descriptors, we need a way to systematically compare and evaluate these descriptors. This PR seeks to enable that by:

- [x] Enabling us to record and save user performances (both the video and the pose information), so that we can develop a library of test performances.
- [x] Recording a few initial test cases, with the potential to add (many) more in the future.
- [x] Implementing a test framework for running our evaluation methods offline on a series of test cases.
- [x] Add nice reporting of the test results, with charts and tables that break down the evaluation method outputs by test case.
- [ ] (optional) Add a job to include this test step as part of our CI pipeline, to ensure that our evaluation methods stay working and to monitor the impact of code changes on evaluation output.

Additionally, this PR does a few big things!

- Runs summary metrics on each leaf dance tree node of the performed section. This gives a set of measurements for different times within a segment. (can easily adjust to run on each sub node).
- Breaks down the dance trees by an additional level (into 4-beat bars, rather than stopping at 8 beat segments). This allows the user to be more specific when practicing.
- Adds frontend code in charge of "distilling" data into a textual representation for consumption by the LLM. Right now, it distills (1) our performance summary, and (2) the dance tree structure
- Changes feedback API to provide more information. Instead of just providing a message and "try again" boolean, it now provides:
    - A coaching reflection (not shown to the user), giving it a space to "think"
    - A feedback message (shown to the user, same as before) about the user's performance
    - A practice recommendation - a specific section they should practice next, or whether the user should repeat the current section.
    - A coaching message (shown to the user), informing the user about the practice recommendation
    - A title for the feedback.

- Adds a text-to-speech interface
- Improves & organizes the settings menu

Closes #63.

### CODE REVIEW

**Comment by j55blanchet** [comment]
@sixuanhan There are definitely some more comments to be added in order to document these classes, interfaces, etc. (+ additions to the README to detail how to do the testing).

I can do those things later, but figured we could get this merged now to unblock you from implementing jerk with the new metric refactoring

**Comment by j55blanchet** [comment]
Additional changes (not mentioned above):

- Settings panel is accessible from any page
- PracticePage is will not record evaluation results when video is paused.

**Comment by j55blanchet** [comment]
Closes #61, #60, #59, #44, #63.

**Review by sixuanhan — APPROVED** [review]
Great changes! Thank you.

**Pull request merged**
