### PR TITLE
feat: Enhanced Tempo Analysis

### PR DESCRIPTION
**Pull request by j55blanchet**
This PR brings more sophisticated tempo analysis to our motion pipeline. This investigation started with the observation (1) that the music beats present in the dance trees did not cover the full duration of the dance, as visible in the screenshot below:

Screen Shot 2023-09-02 at 17 37 30

In addition to that beats being missing on the second half of the song, we have also noticed (2) that the detected bpm, as well as the timing of the beats, were sometimes inaccurate, and (3) the detected bpm and beats seems to vary depending on which machine the pipeline was run on (e.g. laptop at home vs at work; Selena's machine vs mine).

To address this, I added additional beat-detection methods to the tempo_detection module and added plotting to compare the results. Here's an example of the new output plots:

debbieallenchallenge tempo_analysis

TODO: 

- [x] discuss the differences between the different beat calculation methods.
- [x] decide on a method for fixing the issue (perhaps by including the multiple variations of calculated bpm, properly named to denote their individual significance, in the audio analysis result).
- [x] implement the fix; test to make sure it's fixed.
- [x] remove beat_times from db.csv to reduce churn on git changes.

### CODE REVIEW

**Comment by j55blanchet** [comment]
Addresses #40

**Comment by j55blanchet** [comment]
To address gaps in `beat_times`, I created a routine that fills in any gaps in the detected beats and adjusted the code to clearly delineate between `audible_beat_times` and `all_beat_times`. The result is like this:
image

**Comment by j55blanchet** [comment]
I looked into bpm inaccuracies. Here's a chart on which ones seem accurate vs not:
image

**Comment by j55blanchet** [comment]
It's unclear why the detected bpm for those songs is inaccurate. Will require further investigation to get to the bottom of that, but it tends to be for longer clips, which perhaps may have instructions or non-music content that confounds.

**Comment by j55blanchet** [comment]
After these changes, the beats on the frontend will in-fact fill the screen: 
image

**Comment by j55blanchet** [comment]
Playing a few songs at 0.5x speed and looking at the beat timing, it seems to be correct (for those that were correct in the table shared above)!

image

**Comment by j55blanchet** [comment]
**Difference in beat calculation methods** (from <https://librosa.org/doc/main/generated/librosa.beat.plp.html>)
* `librosa.beat.beat_track`: looks at the song holistically. Does a three step process of (1) measuring onset strength, (2) estimating tempo from onset correlation to derive a bpm (3) picking peaks on onset strength approximately consistent with estimated tempo (this identifying audible beats).
* `librosa.beat.plp`: analyzes onsets in frequency domain to find a locally stable tempo, then synthesizes a _pulse_ (half-waves) that conincide with rhythmically salient frames (onset events). We can then take the local maxima of the pulse curve to get beat positions.
    * We then get a global bpm for the song by measuring the inter-peak intervals and doing outlier rejection, assuming the song has a consistent tempo. In the future, we could use plp to handle / model songs with varying tempo.

**Review by sixuanhan — APPROVED** [review]
The tempo analysis looks much better!

**Review by j55blanchet — COMMENTED** [review]
Just verified that the merge didn't introduce any unwanted artifacts!

**Pull request merged**
